name: Compile LaTeX Curriculum Vitae

on:
  push:
    branches: [main]
    paths:
      - "**.tex"
      - "bibliography.bib"
      - "images/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Nome della versione (es. v24-05-01)"
        required: false
      lang:
        description: "Which language to build: it | en | all"
        required: false
        default: "all"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-lang-italian texlive-latex-recommended texlive-latex-extra latexmk texlive-xetex texlive-fonts-recommended

      - name: Get current date
        id: date
        run: echo "today=v$(date +'%y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Compile LaTeX document
        run: |
          case "${{ github.event.inputs.lang || 'all' }}" in
            it)
              pnpm run build:it
              ;;
            en)
              pnpm run build:en
              ;;
            all)
              pnpm run build:all
              ;;
            *)
              echo "Unknown lang '${{ github.event.inputs.lang }}', defaulting to all"
              pnpm run build:all
              ;;
          esac
      - name: Prepare release files list
        id: release_files
        run: |
          case "${{ github.event.inputs.lang || 'all' }}" in
            it)
              echo "files=Tonini_Isaia_CV_it.pdf" >> "$GITHUB_OUTPUT"
              ;;
            en)
              echo "files=Tonini_Isaia_CV_en.pdf" >> "$GITHUB_OUTPUT"
              ;;
            all)
              echo "files=Tonini_Isaia_CV_it.pdf Tonini_Isaia_CV_en.pdf" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "files=Tonini_Isaia_CV_it.pdf Tonini_Isaia_CV_en.pdf" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || steps.date.outputs.today }}
          name: Versione ${{ github.event.inputs.version || steps.date.outputs.today }}
          files: ${{ steps.release_files.outputs.files }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
