name: Compile LaTeX Curriculum Vitae

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "Nome della release"
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.today }}
      release_name: ${{ steps.release_name.outputs.name }}
      tag_name: ${{ steps.tag_name.outputs.tag }}
    steps:
      - name: Get current date
        id: date
        run: echo "today=$(date +'%y-%m-%d')" >> "$GITHUB_OUTPUT"
      
      - name: Set release name
        id: release_name
        run: echo "name=Curriculum Vitae ${{ github.event.inputs.version || steps.date.outputs.today }}" >> "$GITHUB_OUTPUT"
      
      - name: Set tag name
        id: tag_name
        run: echo "tag=CV-${{ github.event.inputs.version || steps.date.outputs.today }}" >> "$GITHUB_OUTPUT"

  build-cv:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Cache TeXLive installation
        uses: actions/cache@v4
        id: texlive-cache
        with:
          path: /usr/share/texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/package*.json') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install TeXLive
        if: steps.texlive-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-lang-italian texlive-latex-recommended texlive-latex-extra latexmk texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Compile Italian CV
        run: pnpm run build:it

      - name: Compile English CV
        run: pnpm run build:en

      - name: Rename PDFs with date
        run: |
          mv Tonini_Isaia_CV_it.pdf Isaia_Tonini_CV_IT-${{ needs.setup.outputs.date }}.pdf
          mv Tonini_Isaia_CV_en.pdf Isaia_Tonini_CV_EN-${{ needs.setup.outputs.date }}.pdf

      - name: Create unified GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          name: ${{ needs.setup.outputs.release_name }}
          files: |
            Isaia_Tonini_CV_IT-${{ needs.setup.outputs.date }}.pdf
            Isaia_Tonini_CV_EN-${{ needs.setup.outputs.date }}.pdf
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.CV_GITHUB_TOKEN }}